/**
 * XXX_LABEL_IN - Types the user picks when creating a column.
 * XXX_LABEL_OUT - Types shown to the user when displaying table info.
 *   PG gives us `XXX_PG_TYPE_OUT`; we replace it with `XXX_LABEL_OUT`.
 * XXX_PG_TYPE_IN - Types used when building a SQL query to create a column.
 * XXX_PG_TYPE_OUT - Type returned by PG when querying table structure.
 * XXX_DEFAULT_VALUE_PG_TYPE_OUT - Types PG uses to describe default column values,
 *   e.g. `'abc'::bpchar`. We strip these keywords.
 */

export enum EPgKeywords {
  ARRAY_LABEL_IN = `ARRAY`,
  ARRAY_LABEL_OUT = `*[]`,
  ARRAY_PG_TYPE_IN = `*[]`,
  ARRAY_PG_TYPE_OUT = `*[]`,

  BIGINT_LABEL_IN = `BIGINT`,
  BIGINT_LABEL_OUT = `BIGINT`,
  BIGINT_PG_TYPE_IN = `BIGINT`,
  BIGINT_PG_TYPE_OUT = `bigint|int8`,

  BIGSERIAL_LABEL_IN = `BIGSERIAL`,
  BIGSERIAL_LABEL_OUT = `BIGSERIAL`,
  BIGSERIAL_PG_TYPE_IN = `BIGINT`,
  BIGSERIAL_PG_TYPE_OUT = `bigint|int8`,

  BOOLEAN_LABEL_IN = `BOOLEAN`,
  BOOLEAN_LABEL_OUT = `BOOLEAN`,
  BOOLEAN_PG_TYPE_IN = `BOOLEAN`,
  BOOLEAN_PG_TYPE_OUT = `boolean|bool`,

  CHAR_LABEL_IN = `CHAR`,
  CHAR_LABEL_OUT = `CHAR#`,
  CHAR_PG_TYPE_IN = `CHARACTER#`,
  CHAR_PG_TYPE_OUT = `character|bpchar`,

  DATE_LABEL_IN = `DATE`,
  DATE_LABEL_OUT = `DATE`,
  DATE_PG_TYPE_IN = `DATE`,
  DATE_PG_TYPE_OUT = `date`,

  DOUBLE_PRECISION_LABEL_IN = `DOUBLE PRECISION`,
  DOUBLE_PRECISION_LABEL_OUT = `DOUBLE PRECISION`,
  DOUBLE_PRECISION_PG_TYPE_IN = `DOUBLE PRECISION`,
  DOUBLE_PRECISION_PG_TYPE_OUT = `double precision|float8`,

  INT_LABEL_IN = `INT`,
  INT_LABEL_OUT = `INT`,
  INT_PG_TYPE_IN = `INTEGER`,
  INT_PG_TYPE_OUT = `integer|int4`,

  NUMERIC_LABEL_IN = `NUMERIC (DECIMAL)`,
  NUMERIC_LABEL_OUT = `NUMERIC#`,
  NUMERIC_PG_TYPE_IN = `NUMERIC#`,
  NUMERIC_PG_TYPE_OUT = `numeric`,

  REAL_LABEL_IN = `REAL`,
  REAL_LABEL_OUT = `REAL`,
  REAL_PG_TYPE_IN = `REAL`,
  REAL_PG_TYPE_OUT = `real|float4`,

  SERIAL_LABEL_IN = `SERIAL`,
  SERIAL_LABEL_OUT = `SERIAL`,
  SERIAL_PG_TYPE_IN = `INTEGER`,
  SERIAL_PG_TYPE_OUT = `integer|int4`,

  SMALLINT_LABEL_IN = `SMALLINT`,
  SMALLINT_LABEL_OUT = `SMALLINT`,
  SMALLINT_PG_TYPE_IN = `SMALLINT`,
  SMALLINT_PG_TYPE_OUT = `smallint|int2`,

  SMALLSERIAL_LABEL_IN = `SMALLSERIAL`,
  SMALLSERIAL_LABEL_OUT = `SMALLSERIAL`,
  SMALLSERIAL_PG_TYPE_IN = `SMALLINT`,
  SMALLSERIAL_PG_TYPE_OUT = `smallint|int2`,

  TEXT_LABEL_IN = `TEXT`,
  TEXT_LABEL_OUT = `TEXT`,
  TEXT_PG_TYPE_IN = `TEXT`,
  TEXT_PG_TYPE_OUT = `text`,

  TIME_WITH_TIME_ZONE_LABEL_IN = `TIME WITH TIME ZONE`,
  TIME_WITH_TIME_ZONE_LABEL_OUT = `TIME+TZ#`,
  TIME_WITH_TIME_ZONE_PG_TYPE_IN = `TIME# WITH TIME ZONE`,
  TIME_WITH_TIME_ZONE_PG_TYPE_OUT = `time with time zone|timetz`,

  TIME_WITHOUT_TIME_ZONE_LABEL_IN = `TIME WITHOUT TIME ZONE`,
  TIME_WITHOUT_TIME_ZONE_LABEL_OUT = `TIME#`,
  TIME_WITHOUT_TIME_ZONE_PG_TYPE_IN = `TIME# WITHOUT TIME ZONE`,
  TIME_WITHOUT_TIME_ZONE_PG_TYPE_OUT = `time without time zone|time`,

  TIMESTAMP_WITH_TIME_ZONE_LABEL_IN = `TIMESTAMP WITH TIME ZONE`,
  TIMESTAMP_WITH_TIME_ZONE_LABEL_OUT = `TIMESTAMP+TZ#`,
  TIMESTAMP_WITH_TIME_ZONE_PG_TYPE_IN = `TIMESTAMP# WITH TIME ZONE`,
  TIMESTAMP_WITH_TIME_ZONE_PG_TYPE_OUT = `timestamp with time zone|timestamptz`,

  TIMESTAMP_WITHOUT_TIME_ZONE_LABEL_IN = `TIMESTAMP WITHOUT TIME ZONE`,
  TIMESTAMP_WITHOUT_TIME_ZONE_LABEL_OUT = `TIMESTAMP#`,
  TIMESTAMP_WITHOUT_TIME_ZONE_PG_TYPE_IN = `TIMESTAMP# WITHOUT TIME ZONE`,
  TIMESTAMP_WITHOUT_TIME_ZONE_PG_TYPE_OUT = `timestamp without time zone|timestamp`,

  UUID_LABEL_IN = `UUID`,
  UUID_LABEL_OUT = `UUID`,
  UUID_PG_TYPE_IN = `UUID`,
  UUID_PG_TYPE_OUT = `uuid`,

  VARCHAR_LABEL_IN = `VARCHAR`,
  VARCHAR_LABEL_OUT = `VARCHAR#`,
  VARCHAR_PG_TYPE_IN = `CHARACTER VARYING#`,
  VARCHAR_PG_TYPE_OUT = `character varying|varchar`,
}
